### PR TITLE
Add dkms support

### PR DESCRIPTION
**Pull request by sergeyksv**
Ubuntu kernel is updating all the time and I find it useful to set dkms build for your driver. Hope you find it useful, if don't not prob.

### CODE REVIEW

**Comment by kuba-moo** [comment]
Thanks, I don't know much about dkms but it looks good :)
Two things about the commit message though:
(1) Could you rename it to something more precise like: "add dkms support"?
(2) Can you add a sign-off to make the change officially licensed under GPL? You can do it by simply calling:
```git commit --amend --no-edit --signoff```

**Comment by sergeyksv** [comment]
I believe I did what you asked.

**Comment by kuba-moo** [comment]
Almost, about the rename - I meant the title of the commit, not the title of pull request :)

**Comment by kuba-moo** [comment]
I fixed the commit message myself. Thanks.

**Pull request closed without merging**
